[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='2083334cc8f89c88fadf6354ce8ab026818f4fcae69ec027aa605e280cc880b1'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
